# 定义一个 Deployment 资源
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance # 指定 Deployment 的名称为 finance
spec:
  replicas: 3 # 设置副本数量为 3
  selector:
    matchLabels:
      app: finance # 根据标签选择器匹配 app=finance 的 Pod
  template:
    metadata:
      labels:
        app: finance # 给 Pod 添加标签 app=finance
    spec:
      containers:
      - name: finance # 容器的名称为 finance
        image: rossning92/finance # 使用 rossning92/finance 镜像
        resources:
          limits:
            memory: "256Mi" # 内存限制为 256MiB
            cpu: "500m" # CPU 限制为 500m（500 毫核）
        ports:
        - containerPort: 5000 # 容器监听的端口为 5000

---
# 定义一个 Service 资源
apiVersion: v1
kind: Service
metadata:
  name: finance-np-service # 指定 Service 的名称为 finance-np-service
spec:
  selector:
    app: finance # 选择标签 app=finance 的 Pod
  type: NodePort # 设置服务类型为 NodePort
  ports:
  - port: 5000 # 服务端口为 5000
    targetPort: 5000 # Pod 的端口为 5000
    nodePort: 30080 # 节点端口为 30080
